### ISSUE TITLE
Support return type "footage" and "timecode"

### ISSUE THREAD

**Issue by jonykalavera** [ndunsworth/python-shotgunorm#22]
This is necesary to fully support shotgun api's types

**Comment by jonykalavera** [comment]
many thanks. i'm working in a lazy resultset feature i need to use shotgunorm with django-tastypie. i don't think its ready yet but i'll let you know to see what do you think.

**Comment by ndunsworth** [comment]
I took a peek at your lazy search iterator, have a look at SgBufferedSearchIterator and SgSearchIterator added to the develop branch over the weekend.
